using GestureClip.Core.Gestures;

namespace GestureClip.App.ViewModels;

public static class GestureActionText
{
    public static string Name(BuiltInGestureAction action) => action switch
    {
        BuiltInGestureAction.None => "未绑定",
        BuiltInGestureAction.Copy => "复制",
        BuiltInGestureAction.Paste => "粘贴",
        BuiltInGestureAction.Cut => "剪切",
        BuiltInGestureAction.SelectAll => "全选",
        BuiltInGestureAction.Undo => "撤销",
        BuiltInGestureAction.Redo => "重做",
        BuiltInGestureAction.Enter => "回车确认",
        BuiltInGestureAction.Escape => "取消 / Esc",
        BuiltInGestureAction.Delete => "删除",
        BuiltInGestureAction.Backspace => "退格",
        BuiltInGestureAction.OpenClipboardOverlay => "打开剪贴板历史",
        BuiltInGestureAction.PasteLatestClipboardItem => "粘贴最近一条历史",
        BuiltInGestureAction.SendAltLeft => "后退",
        BuiltInGestureAction.SendAltRight => "前进",
        BuiltInGestureAction.MinimizeForegroundWindow => "最小化当前窗口",
        BuiltInGestureAction.CloseForegroundWindow => "关闭当前窗口",
        BuiltInGestureAction.PasteAndEnter => "粘贴并回车",
        BuiltInGestureAction.NewTab => "新建标签页",
        BuiltInGestureAction.NextTab => "下一个标签页",
        BuiltInGestureAction.PreviousTab => "上一个标签页",
        BuiltInGestureAction.ReopenClosedTab => "重新打开标签页",
        BuiltInGestureAction.Refresh => "刷新",
        BuiltInGestureAction.CloseTab => "关闭标签页",
        BuiltInGestureAction.StartMenu => "开始菜单",
        BuiltInGestureAction.ShowDesktop => "显示桌面",
        BuiltInGestureAction.SwitchApp => "切换 App",
        BuiltInGestureAction.TaskSwitcher => "任务切换",
        BuiltInGestureAction.PlayPause => "播放 / 暂停",
        BuiltInGestureAction.VolumeUp => "音量 +",
        BuiltInGestureAction.VolumeDown => "音量 -",
        BuiltInGestureAction.Mute => "静音",
        BuiltInGestureAction.PreviousTrack => "上一曲",
        BuiltInGestureAction.NextTrack => "下一曲",
        BuiltInGestureAction.TaskManager => "任务管理器",
        BuiltInGestureAction.SystemSettings => "系统设置",
        BuiltInGestureAction.Sleep => "休眠",
        BuiltInGestureAction.ZoomIn => "放大",
        BuiltInGestureAction.ZoomOut => "缩小",
        BuiltInGestureAction.ResetZoom => "重置缩放",
        BuiltInGestureAction.Home => "Home 键",
        BuiltInGestureAction.End => "End 键",
        BuiltInGestureAction.PageUp => "PageUp",
        BuiltInGestureAction.PageDown => "PageDown",
        BuiltInGestureAction.Screenshot => "截图",
        BuiltInGestureAction.NextVirtualDesktop => "下一个桌面",
        BuiltInGestureAction.PreviousVirtualDesktop => "上一个桌面",
        BuiltInGestureAction.FullScreen => "全屏",
        BuiltInGestureAction.PinWindow => "置顶窗口",
        BuiltInGestureAction.LeftMouseClick => "鼠标左键点击",
        BuiltInGestureAction.RightMouseClick => "鼠标右键点击",
        _ => action.ToString()
    };

    public static string Shortcut(BuiltInGestureAction action) => action switch
    {
        BuiltInGestureAction.Copy => "Ctrl + C",
        BuiltInGestureAction.Paste => "Ctrl + V",
        BuiltInGestureAction.Cut => "Ctrl + X",
        BuiltInGestureAction.SelectAll => "Ctrl + A",
        BuiltInGestureAction.Undo => "Ctrl + Z",
        BuiltInGestureAction.Redo => "Ctrl + Y",
        BuiltInGestureAction.Enter => "Enter",
        BuiltInGestureAction.Escape => "Esc",
        BuiltInGestureAction.Delete => "Delete",
        BuiltInGestureAction.Backspace => "Backspace",
        BuiltInGestureAction.SendAltLeft => "Alt + ←",
        BuiltInGestureAction.SendAltRight => "Alt + →",
        BuiltInGestureAction.OpenClipboardOverlay => "Ctrl + `",
        BuiltInGestureAction.PasteLatestClipboardItem => "历史最近一条",
        BuiltInGestureAction.PasteAndEnter => "Ctrl + V, Enter",
        BuiltInGestureAction.NewTab => "Ctrl + T",
        BuiltInGestureAction.NextTab => "Ctrl + Tab",
        BuiltInGestureAction.PreviousTab => "Ctrl + Shift + Tab",
        BuiltInGestureAction.ReopenClosedTab => "Ctrl + Shift + T",
        BuiltInGestureAction.Refresh => "F5",
        BuiltInGestureAction.CloseTab => "Ctrl + W",
        BuiltInGestureAction.StartMenu => "Win",
        BuiltInGestureAction.ShowDesktop => "Win + D",
        BuiltInGestureAction.SwitchApp => "Alt + Tab",
        BuiltInGestureAction.TaskSwitcher => "Ctrl + Alt + Tab",
        BuiltInGestureAction.PlayPause => "Media",
        BuiltInGestureAction.VolumeUp => "Volume +",
        BuiltInGestureAction.VolumeDown => "Volume -",
        BuiltInGestureAction.Mute => "Mute",
        BuiltInGestureAction.PreviousTrack => "Previous Track",
        BuiltInGestureAction.NextTrack => "Next Track",
        BuiltInGestureAction.TaskManager => "taskmgr",
        BuiltInGestureAction.SystemSettings => "Win + I",
        BuiltInGestureAction.Sleep => "Sleep",
        BuiltInGestureAction.ZoomIn => "Ctrl + =",
        BuiltInGestureAction.ZoomOut => "Ctrl + -",
        BuiltInGestureAction.ResetZoom => "Ctrl + 0",
        BuiltInGestureAction.Home => "Home",
        BuiltInGestureAction.End => "End",
        BuiltInGestureAction.PageUp => "PageUp",
        BuiltInGestureAction.PageDown => "PageDown",
        BuiltInGestureAction.Screenshot => "Win + Shift + S",
        BuiltInGestureAction.NextVirtualDesktop => "Ctrl + Win + →",
        BuiltInGestureAction.PreviousVirtualDesktop => "Ctrl + Win + ←",
        BuiltInGestureAction.FullScreen => "F11",
        BuiltInGestureAction.PinWindow => "预留",
        BuiltInGestureAction.LeftMouseClick => "鼠标左键",
        BuiltInGestureAction.RightMouseClick => "鼠标右键",
        _ => ""
    };
}
