namespace GestureClip.Core.Workstation;

public sealed record WorkstationDashboardSnapshot(
    string Title,
    string Subtitle,
    TimeSpan TimeUntilOffWork,
    decimal TodayEarned,
    decimal MonthEarned,
    int DaysUntilPayday,
    bool IsFishing,
    TimeSpan CurrentFishingDuration,
    decimal CurrentFishingValue,
    decimal TodayFishingValue,
    int CopyCount,
    int PasteCount,
    int GestureCount,
    int EstimatedSavedClicks,
    string WorkStatusText,
    WorkTimeStage WorkTimeStage = WorkTimeStage.OffWork,
    string WorkStageText = "已下班",
    string BearStatusText = "低功耗小熊",
    string BearLineText = "今天也在低功耗运行。",
    decimal MinuteValue = 0m,
    TimeSpan TodayFishingDuration = default,
    int OpenClipboardCount = 0,
    TimeSpan TodayWorkDuration = default,
    TimeSpan EffectiveWorkDuration = default,
    TimeSpan ContinuousWorkDuration = default,
    DateTimeOffset? NextRestReminderAt = null,
    int RestReminderCount = 0,
    string RestRiskText = "正常",
    bool RestReminderEnabled = true,
    bool SprintActive = false,
    string SprintSuggestionText = "保持节奏，稳住输出。",
    TimeSpan OvertimeDuration = default,
    string DailyRatingText = "稳定输出型",
    string DailyReportText = "",
    string SalaryHintText = "仅供娱乐估算，不作财务依据。",
    string StageAccentColor = "#60A5FA",
    string StageStartColor = "#1D4ED8",
    string StageEndColor = "#111827",
    double WorkdayProgress = 0d,
    string RestRiskLevel = "normal");
